# Generated by Django 3.2 on 2021-04-24 06:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brands', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=255)),
                ('kcal_100g', models.IntegerField()),
                ('off_id', models.CharField(max_length=255, null=True)),
                ('categories', models.ManyToManyField(
                    to='openfoodfacts.Category')),
            ],
        ),
    ]
