# Generated by Django 3.2 on 2021-05-04 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openfoodfacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('product_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='product',
                        to='openfoodfacts.product')),
                ('substitute_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='substitute',
                    to='openfoodfacts.product')),
                ('user_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user',
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
