# Generated by Django 3.2.1 on 2021-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0005_auto_20210510_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
