# Generated by Django 3.2 on 2021-05-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_substitute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='substitute',
        ),
    ]
