language: python

python:
  - "3.8"
env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings"
services:
  - postgresql
addons:
  chrome: stable
install:
  - pipenv install
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
  - yum localinstall google-chrome-stable_current_x86_64.rpm
before_script:
  - psql -c 'create database pur_beurre;'
  - psql -c 'create user django;'
  - psql -c 'ALTER USER django CREATEDB;'
  - psql -c 'GRANT all privileges ON DATABASE pur_beurre TO django;'
script:
  - export SECRET_KEY='test'
  - whereis google-chrome-stable
  - whereis chromedriver
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
