language: python

python:
  - "3.8"
env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings"
services:
  - postgresql
install:
  - pipenv install
before_script:
  - psql -c 'create user django;'
  - psql -c 'create database pur_beurre;' -U django
script:
  - export SECRET_KEY='test'
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
