language: python

python:
  - "3.8"
env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings"
services:
  - postgresql
install:
  - pipenv install
before_script:
  - psql -c 'create database pur_beurre;'
  - psql -c 'create user django;'
  - psql -c 'GRANT all privileges ON DATABASE pur_beurre TO django;'
script:
  - export SECRET_KEY='test'
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test

