language: python

python:
  - "3.8"
env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings"
services:
  - postgresql
addons:
  chrome: stable
install:
  - pipenv install
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
  - psql -c 'create database pur_beurre;'
  - psql -c 'create user django;'
  - psql -c 'ALTER USER django CREATEDB;'
  - psql -c 'GRANT all privileges ON DATABASE pur_beurre TO django;'
script:
  - export SECRET_KEY='test'
  - whereis google-chrome
  - whereis chromedriver
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
