language: python

python:
  - "3.8"
env:
  - SECRET_KEY='TEST'
services:
  - postgresql
install:
  - pipenv install
before_script:
  - psql -c 'create database pur_beurre;'
  - psql -c 'create user django;'
  - psql -c 'GRANT all privileges ON DATABASE pur_beurre TO django;'
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
