# Generated by Django 3.2 on 2021-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_off_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
